config/routes.rb
TwitterClone::Application.routes.draw do
  get "sessions/new"

  resources :story_nodes
  resources :comments

  resources :stories do
    member do
      get 'view'
    end
  end

  resources :storypaths, controller: "storypath"
  resources :users, controller: "users"
  resources :sessions, :only => [:new,
                                 :create,
                                 :destroy]

  root :to => "frontpage#frontpage"

  match "sign_up" => "users#sign_up"
  match "sign_in" => "sessions#new"
  match "sign_out" => "sessions#destroy"

  match "home" => "users#home"
  match "user_create" => "users#create"
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope :order => 'created_at ASC'

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user

end

app/models/story.rb
class Story < ActiveRecord::Base
  acts_as_commentable
  has_many :story_nodes
end

app/models/story_branch.rb
class StoryBranch < ActiveRecord::Base
  belongs_to :from_node, :class_name => "StoryNode", :foreign_key => :from_node_id
  belongs_to :to_node,   :class_name => "StoryNode", :foreign_key => :to_node_id
end

app/models/story_node.rb
class StoryNode < ActiveRecord::Base
  acts_as_commentable
  belongs_to :story
  belongs_to :author, :class_name => "User"

  has_many :story_branches, :class_name => "StoryBranch",
           :foreign_key => :from_node_id
  has_many :branches, :through => :story_branches, :source => :to_node
  has_many :previous_story_branches, :class_name => "StoryBranch",
           :foreign_key => :to_node_id
  has_many :previous_branches, :through => :previous_story_branches,
           :source => :from_node
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :story_nodes
  has_many :comments

  def self.authenticate?(username)
    find_by_username username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate, :only => [:create]

  def create
    @story_node = StoryNode.find(params[:comment][:story_node_id]) 
    if @story_node.nil? 
      puts "Couldn't find storynode_id"
    end
    
    @comment = Comment.new
    @comment.title = params[:comment][:title]
    @comment.comment = params[:comment][:comment]
    @comment.user = current_user
    
    @story_node.comments << @comment
    
    @comments = Comment.all

    redirect_to @story_node
  end
end

app/controllers/frontpage_controller.rb
class FrontpageController < ApplicationController
  def frontpage
    @title = "Home"
    @user = User.new

    respond_to do |format|
      @stories = Story.all
      format.html { render 'frontpage' }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end

  def create
    user = User.authenticate?(params[:sessions][:username])

    if user.nil?
      user = User.create(:username => params[:sessions][:username])
    end

    sign_in user

    redirect_back_or :controller => :frontpage, :action => :frontpage
  end

  def destroy
    sign_out
    redirect_to :controller => :frontpage, :action => :frontpage
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_filter :authenticate, :only => [:new, :create]

  def index
    @stories = Story.all

    respond_to do |format|
      format.html
    end
  end

  def new
    @story = Story.new
    respond_to do |format|
      format.html
    end
  end

  def edit
    @story = Story.find(params[:story][:id])
  end

  def create
    @story = Story.new(params[:story])

    @story_node = StoryNode.new
    @story_node.save
    @story.start_node = @story_node.id

    @story.save

    @story_node.story_id = @story.id
    @story_node.author = current_user
    @story_node.save

    redirect_to edit_story_node_path(@story_node)
  end

  def show
    @story = Story.find(params[:id])
    respond_to do |format|
      format.html { redirect_to StoryNode.find(@story.start_node) }
      format.json { render :json, @story }
    end
  end

  def update
    @story = Story.find(params[:id])
    if @story.update_attributes(params[:story])
      flash.now[:success] = "Content updated."
      redirect_to @story
    else
      @title = "Edit user"
      render 'edit'
    end
  end

  def failure
  end
end

app/controllers/story_nodes_controller.rb
class StoryNodesController < ApplicationController
  before_filter :authenticate, :only => [:new, :create]
  before_filter :correct_user, :only => [:edit, :update]

  def edit
    @story_node = StoryNode.find(params[:id])
  end

  def update
    @story_node = StoryNode.find(params[:id])
    @story_node.title = params[:story_node][:title]
    @story_node.content = params[:story_node][:content]
    @story_node.save

    redirect_to @story_node
  end

  def new
    @story_node = StoryNode.new
  end

  def create
    @story_node = StoryNode.new
    @story_branch = StoryBranch.new
    @prev_story_node = StoryNode.find(params[:story_node][:parent])

    @story_node.title = params[:story_node][:title]
    @story_node.content = params[:story_node][:content]

    @story_node.story_id = @prev_story_node.story_id
    @story_node.author = current_user
    @story_node.save

    @story_branch.from_node_id = params[:story_node][:parent]
    @story_branch.to_node_id = @story_node.id
    @story_branch.save

    redirect_to @story_node
  end

  def show
    @story_node = StoryNode.find(params[:id])
    @story = Story.where(:start_node => @story_node.id).first
    @comment = Comment.new
    @comments = @story_node.comments.all
  end

  private
    def correct_user
      author = StoryNode.find(params[:id]).author
      redirect_to(root_path) unless current_user?(author)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(params[:user])
    @title = @user.user_name
    
    respond_to do |format|
      if @user.save
        flash[:success] = "Welcome to BranchItOut!"
        format.html {render action: "user_home"}
      else
        format.html {render action: "failure"}
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def setTitleBasedOnPage
    base_title = "Branch It Out"

    if @title.nil?
      base_title
    else
        "#{ @title } | #{ base_title }"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/frontpage_helper.rb
module FrontpageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    # TODO chris jan 9, 2011 deal with case for deleted users more elegantly
    if session[:user_id]
      if @current_user
        return @current_user
      elsif User.exists?(:id => session[:user_id])
        @current_user = User.find(session[:user_id])
      else
        sign_out
      end
    end
  end

  def current_user=(user)
    @current_user = user
  end

  def sign_in(user)
    session[:user_id] = user.id
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    session[:user_id] = nil
    current_user = nil
  end

  def current_user?(user)
    !current_user.nil? && user == current_user
  end

  def deny_access
    store_location
    redirect_to sign_in_path, :notice => "Please sign in to access this page."
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end

  def authenticate
    deny_access unless signed_in?
  end

  private
    def store_location
      session[:return_to] = request.fullpath
    end

    def clear_return_to
      session[:return_to] = nil
    end
end

app/helpers/story_helper.rb
module StoryHelper
end

app/helpers/story_nodes_helper.rb
module StoryNodesHelper
end

app/helpers/storypath_helper.rb
module StorypathHelper
end

app/helpers/storypaths_helper.rb
module StorypathsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.title %> - <%= comment.comment %></td>
  </tr>
  </br>
<% end %>

app/views/frontpage/frontpage.html.erb
<%= render 'templates/story_templates.html' %>

<div class="row">
  <div class="offset1">
    <h2 class="headingLine">Read a Story</h1>
  </div>
</div>

<div id="frontpage" class="row">
  <div id="story-list-container" class="span8 offset1">
    <ul id="story-list-placeholder"></ul>
  </div>

  <div class="span5 sellingBox">
    <h1>Is the time write?</h1>
    <p>Then it's time to...</p>
    <a class="submit_button" href="/stories/new">
      Create a Story
    </a>
  </div>
</div>

<script type="text/javascript">
  window.BranchItOut.stories = <%= raw @stories.to_json %>;
</script>

<div class="fb-like" data-href="http://www.branchitout.com" data-send="false" data-width="450" data-show-faces="true"></div>

<%= requirejs_include_tag "home_page" %>

app/views/stories/edit.html.erb
<p>
  	<b>Title:</b>
  	<%= @story.title %>
  	</br>
  	<b>Content:</b>
  	<%= @story.content %>

	<%= form_for @story, :url => story_path do |form| %>
		<%= form.text_area :content, :class => "stories_text_area", :placeholder => @story.content %>
		</br>
    <%= form.submit "Save", :class => "btn saveButton" %>
	<% end %>
</p>

app/views/stories/failure.html.erb
failure

app/views/stories/index.html.erb
<% @stories.each do |story| %>
  <tr>
    <td><%= story.id %> - <%= story.title %></td>
  </tr>
  </br>
<% end %>

app/views/stories/new.html.erb
<div class="editItemForm row">
  <div class="row">
    <div class="span6 offset2">
      <h1>Create a Story</h1>
    </div>
  </div>
  <div class="row">
    <%= form_for @story do |form| %>
      <div class="row">
        <div class="offset2 span14">
          <label for="title">Story Title</label>
          <div class="input">
            <%= form.text_field :title, :placeholder => "Story Title", :class => "span10 mainField" %>
          </div>
          <div class="clearfix"></div>
          <!--<%= form.text_field :category, :placeholder => "Category"%>
          </br>-->
          <label for="description">Description</label>
          <div class="input">
            <%= form.text_area :description, :placeholder => "Description", :class => "span10 offset2 descriptionField" %>
          </div>
          <div class="clearfix"></div>
          <div class="row">
            <div class="span4 offset2">
              <%= form.submit "Create Story", :class => "btn saveButton" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/stories/show.html.erb
<p>
  <b>Title:</b>
  <%= @story.title %>
  </br>
  <b>Description:</b>
  <%= @story.description %>

  <br />
  <a href="/story_nodes/<%= @story.start_node %>">continue to the story</a>
  <br />
</p>

app/views/story_nodes/edit.html.erb
<div class="editItemForm row">
  <div class="row">
    <div class="span6 offset2">
      <h1>Edit a Story</h1>
    </div>
  </div>
  <div class="row">
    <%= form_for @story_node, :method => :put do |form| %>
      <div class="row">
        <div class="offset2 span14">
          <label for="title">Branch Title</label>
          <div class="input">
            <%= form.text_field :title, :placeholder => @story_node.title || "Branch Title", :class => "span10 mainField" %>
          </div>
          <div class="clearfix"></div>
          <label for="content">Branch Content</label>
          <div class="input">
		        <%= form.text_area :content, :class => "stories_text_area", :placeholder => @story_node.content || "Branch Content", :class => "span10 offset2 contentField" %>
          </div>
          <div class="clearfix"></div>
          <div class="row">
            <div class="span4 offset2">
              <%= form.submit "Save", :class => "btn saveButton" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/story_nodes/new.html.erb
<div class="editItemForm row">
  <div class="row">
    <div class="span6 offset2">
      <h1>Create a Branch</h1>
    </div>
  </div>
  <div class="row">
    <%= form_for @story_node, :method => :put do |form| %>
      <div class="row">
        <div class="offset2 span14">
          <label for="title">Branch Title</label>
          <div class="input">
            <%= form.text_field :title, :placeholder => @story_node.title || "Branch Title", :class => "span10 mainField" %>
          </div>
          <div class="clearfix"></div>
          <label for="content">Branch Content</label>
          <div class="input">
		        <%= form.text_area :content, :class => "stories_text_area", :placeholder => @story_node.content || "Branch Content", :class => "span10 offset2 contentField" %>
          </div>
          <div class="clearfix"></div>
          <div class="row">
            <div class="span4 offset2">
              <%= form.submit "Create", :class => "btn saveButton" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/story_nodes/show.html.erb
<div class="row">
  <div class="span4">
    <h1 class="story-title"><%= @story_node.story.title %></h1>
  </div>

  <div class="span10 offset1">
    <div id="story-node-placeholder"></div>
  </div>
</div>
<br />
<div class="row">
  <div class="span10 offset5">
    <% if !@comments.nil? %>
      <div class="comments-container">
        <% @comments.each do |comment| %>
          <div class="comment">
            <h3><%= comment.user.username %></h3>
            <p><%= comment.comment %></p>
          </div>
        <% end %>
      </div>
    <% end %>

    <% if signed_in? %>
      <h2>Post a comment</h2>
      <div class="commentForm">
        <%= form_for @comment, :method => :post do |form| %>
          <!--<%= form.text_field :title, :placeholder => "Title" %>
          </br>-->

          <%= form.text_area :comment, :placeholder => "Comment" %>

          </br>

          <%= form.submit "Post Comment", :class => "btn primary postCommentButton" %>

          <% if !@story_node.nil? %>
            <%= form.hidden_field 'story_node_id', :value => @story_node.id %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  window.BranchItOut.storyNode = <%= raw @story_node.to_json %>;
  window.BranchItOut.storyNode.parent = <%= raw @story_node.previous_branches[0].to_json %>;
  window.BranchItOut.storyNode.branches = <%= raw @story_node.branches.to_json %>;
  window.BranchItOut.storyNode.author = {
    id       : <%= raw @story_node.author.id.to_json %>,
    username : <%= raw @story_node.author.username.to_json %>
  };
</script>

<%= requirejs_include_tag 'story_node_page' %>

<%= render 'templates/story_node_templates.html' %>

<!--
<div class="fb-like" data-href=<%= request.url %> data-send="false" data-width="450" data-show-faces="true"></div>
-->