config/routes.rb
TwitterClone::Application.routes.draw do
  get "sessions/new"

  resources :story_nodes
  resources :comments

  resources :stories do
    member do
      get 'view'
    end
  end

  resources :storypaths, controller: "storypath"
  resources :users, controller: "users"
  resources :sessions, :only => [:new,
                                 :create,
                                 :destroy]

  root :to => "frontpage#frontpage"

  match "sign_up" => "users#sign_up"
  match "sign_in" => "sessions#new"
  match "sign_out" => "sessions#destroy"

  match "home" => "users#home"
  match "user_create" => "users#create"
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope :order => 'created_at ASC'

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user

end

app/models/story.rb
class Story < ActiveRecord::Base
  acts_as_commentable
  has_many :story_nodes
end

app/models/story_branch.rb
class StoryBranch < ActiveRecord::Base
  belongs_to :from_node, :class_name => "StoryNode", :foreign_key => :from_node_id
  belongs_to :to_node,   :class_name => "StoryNode", :foreign_key => :to_node_id
end

app/models/story_node.rb
class StoryNode < ActiveRecord::Base
  acts_as_commentable
  belongs_to :story
  belongs_to :author, :class_name => "User"

  has_many :story_branches, :class_name => "StoryBranch",
           :foreign_key => :from_node_id
  has_many :branches, :through => :story_branches, :source => :to_node
  has_many :previous_story_branches, :class_name => "StoryBranch",
           :foreign_key => :to_node_id
  has_many :previous_branches, :through => :previous_story_branches,
           :source => :from_node
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :story_nodes
  has_many :comments

  def self.authenticate?(username)
    find_by_username username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate, :only => [:create]

  def create
    @story_node = StoryNode.find(params[:comment][:story_node_id]) 
    if @story_node.nil? 
      puts "Couldn't find storynode_id"
    end
    
    @comment = Comment.new
    @comment.title = params[:comment][:title]
    @comment.comment = params[:comment][:comment]
    @comment.user = current_user
    
    @story_node.comments << @comment
    
    @comments = Comment.all

    redirect_to @story_node
  end
end

app/controllers/frontpage_controller.rb
class FrontpageController < ApplicationController
  def frontpage
    @title = "Home"
    @user = User.new

    respond_to do |format|
      @stories = Story.all
      format.html { render 'frontpage' }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end

  def create
    user = User.authenticate?(params[:sessions][:username])

    if user.nil?
      user = User.create(:username => params[:sessions][:username])
    end

    sign_in user

    redirect_back_or :controller => :frontpage, :action => :frontpage
  end

  def destroy
    sign_out
    redirect_to :controller => :frontpage, :action => :frontpage
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_filter :authenticate, :only => [:new, :create]

  def index
    @stories = Story.all

    respond_to do |format|
      format.html
    end
  end

  def new
    @story = Story.new
    respond_to do |format|
      format.html
    end
  end

  def edit
    @story = Story.find(params[:story][:id])
  end

  def create
    @story = Story.new(params[:story])

    @story_node = StoryNode.new
    @story_node.save
    @story.start_node = @story_node.id

    @story.save

    @story_node.story_id = @story.id
    @story_node.author = current_user
    @story_node.save

    redirect_to edit_story_node_path(@story_node)
  end

  def show
    @story = Story.find(params[:id])
    respond_to do |format|
      format.html { redirect_to StoryNode.find(@story.start_node) }
      format.json { render :json, @story }
    end
  end

  def update
    @story = Story.find(params[:id])
    if @story.update_attributes(params[:story])
      flash.now[:success] = "Content updated."
      redirect_to @story
    else
      @title = "Edit user"
      render 'edit'
    end
  end

  def failure
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(params[:user])
    @title = @user.user_name
    
    respond_to do |format|
      if @user.save
        flash[:success] = "Welcome to BranchItOut!"
        format.html {render action: "user_home"}
      else
        format.html {render action: "failure"}
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def setTitleBasedOnPage
    base_title = "Branch It Out"

    if @title.nil?
      base_title
    else
        "#{ @title } | #{ base_title }"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/frontpage_helper.rb
module FrontpageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    # TODO chris jan 9, 2011 deal with case for deleted users more elegantly
    if session[:user_id]
      if @current_user
        return @current_user
      elsif User.exists?(:id => session[:user_id])
        @current_user = User.find(session[:user_id])
      else
        sign_out
      end
    end
  end

  def current_user=(user)
    @current_user = user
  end

  def sign_in(user)
    session[:user_id] = user.id
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    session[:user_id] = nil
    current_user = nil
  end

  def current_user?(user)
    !current_user.nil? && user == current_user
  end

  def deny_access
    store_location
    redirect_to sign_in_path, :notice => "Please sign in to access this page."
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end

  def authenticate
    deny_access unless signed_in?
  end

  private
    def store_location
      session[:return_to] = request.fullpath
    end

    def clear_return_to
      session[:return_to] = nil
    end
end

app/helpers/story_helper.rb
module StoryHelper
end

app/helpers/story_nodes_helper.rb
module StoryNodesHelper
end

app/helpers/storypath_helper.rb
module StorypathHelper
end

app/helpers/storypaths_helper.rb
module StorypathsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/Shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> 
        prohibited this user from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_topbar.html.erb
<div id="header" class="row">
  <div class="span4">
    <a href=<%= root_path %>>
      <%= image_tag("logo.png", :size => "175x100", :alt => "Branch it out") %>
    </a>
  </div>
  <div class="span5">
    <h2 class="tagLine">Your Path. Your choice.</h2>
  </div>
  <div class="span7">
    <% if signed_in? %>
      <div class="user-status-container">
        <span>
          <a class="btn primary loginButton" href="<%= sign_out_path %>">Logout</a>
          <span class="welcomeLine">Welcome <strong><%= current_user.username %></strong></span>
        </span>
      </div>
    <% else %>
      <div class="user-status-container">
        <span>
          <a class="btn primary loginButton" href="<%= sign_in_path %>">Login</a>
          <span class="welcomeLine">Welcome <strong>Guest</strong></span>
        </span>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= setTitleBasedOnPage %></title>
    <link rel="icon" href="/assets/favicon.ico" type="image/ico" />
    <%= stylesheet_link_tag   "application" %>
    <%= csrf_meta_tags %>

    <script type="text/javascript">
      window.BranchItOut = {
        currentUser : <%= raw current_user.to_json %>
      };
    </script>
  </head>

  <body>
    <div id="fb-root"></div>
    <script>
      /*window.fbAsyncInit = function() {
        FB.init({
          appId      : 'YOUR_APP_ID', // App ID
          channelUrl : '//WWW.YOUR_DOMAIN.COM/channel.html', // Channel File
          status     : true, // check login status
          cookie     : true, // enable cookies to allow the server to access the session
          xfbml      : true  // parse XFBML
        });
      };
      // Additional initialization code here

      // Load the SDK Asynchronously
      (function(d){
        var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
        js = d.createElement('script'); js.id = id; js.async = true;
        js.src = "//connect.facebook.net/en_US/all.js";
        d.getElementsByTagName('head')[0].appendChild(js);
      }(document));
      */
    </script>

    <div id="fb-root"></div>
    <script>
      /*(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=217686564916136";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
      */
    </script>

    <div class="container">
      <%= render 'layouts/topbar' %>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
      </section>

      <%= yield %>

      <br/>
      <br/>
      <br/>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>